declare const messages: {
    ERROR: string;
    SUCCESS: string;
    NOT_FOUND: string;
    BAD_REQUEST: string;
    UNAUTHORIZED: string;
    FORBIDDEN: string;
    TOO_MANY_REQUESTS: string;
    VALIDATION_FAILED: string;
    CONFLICT: string;
    PAYMENT_REQUIRED: string;
    GONE: string;
    INTERNAL_SERVER_ERROR: string;
    SERVICE_UNAVAILABLE: string;
    GATEWAY_TIMEOUT: string;
    LOGIN_SUCCESS: string;
    LOGIN_FAILED: string;
    LOGOUT_SUCCESS: string;
    SESSION_EXPIRED: string;
    OTP_SENT: string;
    OTP_ALREADY_SENT: string;
    INVALID_OTP: string;
    RATE_LIMIT_EXCEEDED: string;
    FILE_UPLOAD_SUCCESS: string;
    FILE_UPLOAD_FAILED: string;
    FILE_NOT_FOUND: string;
    RESOURCE_CREATED: string;
    RESOURCE_UPDATED: string;
    RESOURCE_DELETED: string;
    WELCOME: string;
    GOODBYE: string;
};
export default messages;
export type MessageKey = keyof typeof messages;
