const reshttp = {
  // Informational Responses (1xx)
  continueCode: 100,
  continueMessage: "The server has received the request headers and the client may proceed with the request body.",
  switchingProtocolsCode: 101,
  switchingProtocolsMessage: "The requester has asked the server to switch protocols.",
  processingCode: 102,
  processingMessage: "The server has received the request and is processing it, but no response is available yet.",
  earlyHintsCode: 103,
  earlyHintsMessage: "The server is sending preliminary headers before the final response.",

  // Success Responses (2xx)
  okCode: 200,
  okMessage: "The request was successful.",
  createdCode: 201,
  createdMessage: "The request was successful, and a new resource was created.",
  acceptedCode: 202,
  acceptedMessage: "The request has been received but has not yet been acted upon.",
  nonAuthoritativeInformationCode: 203,
  nonAuthoritativeInformationMessage: "The response contains modified metadata not from the origin server.",
  noContentCode: 204,
  noContentMessage: "The request was successful, but there is no content to send in the response.",
  resetContentCode: 205,
  resetContentMessage: "The server has fulfilled the request and instructs the client to reset the document view.",
  partialContentCode: 206,
  partialContentMessage: "The server is delivering only part of the resource due to a range header sent by the client.",

  // Redirection Messages (3xx)
  multipleChoicesCode: 300,
  multipleChoicesMessage: "The request has multiple possible responses.",
  movedPermanentlyCode: 301,
  movedPermanentlyMessage: "The resource has been moved permanently to a new URL.",
  foundCode: 302,
  foundMessage: "The resource is temporarily located at a different URL.",
  seeOtherCode: 303,
  seeOtherMessage: "The client should retrieve the resource at another URL with a GET request.",
  notModifiedCode: 304,
  notModifiedMessage: "The resource has not been modified since the last request.",
  temporaryRedirectCode: 307,
  temporaryRedirectMessage: "The resource is temporarily located at a different URL, but the original method should be used.",
  permanentRedirectCode: 308,
  permanentRedirectMessage: "The resource has been permanently moved to a new URL, and the original method should be used.",

  // Client Errors (4xx)
  badRequestCode: 400,
  badRequestMessage: "The server could not understand the request due to invalid syntax.",
  unauthorizedCode: 401,
  unauthorizedMessage: "The client must authenticate itself to get the requested response.",
  paymentRequiredCode: 402,
  paymentRequiredMessage: "Payment is required to access the resource.",
  forbiddenCode: 403,
  forbiddenMessage: "The client does not have permission to access the requested resource.",
  notFoundCode: 404,
  notFoundMessage: "The requested resource was not found on the server.",
  methodNotAllowedCode: 405,
  methodNotAllowedMessage: "The request method is not allowed for the requested resource.",
  notAcceptableCode: 406,
  notAcceptableMessage: "The server cannot produce a response matching the accept headers sent in the request.",
  conflictCode: 409,
  conflictMessage: "The request could not be processed due to a conflict with the current state of the resource.",
  goneCode: 410,
  goneMessage: "The requested resource is no longer available on the server.",
  lengthRequiredCode: 411,
  lengthRequiredMessage: "The server requires a Content-Length header field in the request.",
  iamATeapotCode: 418,
  iamATeapotMessage: "I'm a teapot.",
  tooManyRequestsCode: 429,
  tooManyRequestsMessage: "The client has sent too many requests in a given amount of time.",

  // Server Errors (5xx)
  internalServerErrorCode: 500,
  internalServerErrorMessage: "The server encountered an unexpected condition that prevented it from fulfilling the request.",
  notImplementedCode: 501,
  notImplementedMessage: "The server does not support the functionality required to fulfill the request.",
  badGatewayCode: 502,
  badGatewayMessage: "The server received an invalid response from the upstream server.",
  serviceUnavailableCode: 503,
  serviceUnavailableMessage: "The server is currently unable to handle the request due to maintenance or overload.",
  gatewayTimeoutCode: 504,
  gatewayTimeoutMessage: "The server did not receive a timely response from the upstream server.",
};

export default reshttp;
export { reshttp };
